language: objective-c
install:
- gem install xcpretty
script:
- set -o pipefail && xcodebuild -project "TestApp.xcodeproj" -scheme "TestApp" build analyze
notifications:
    slack: xs-labs:FXh1yLXNkpcVxKZhZU6icdhI
